import { Subjects } from '@/types';

export const mockSubjects: Subjects[] = [
  {
    id: 1,
    name: 'Introduction to Computer Science',
    code: 'CS101',
    description: 'Fundamental concepts of computer science including algorithms, data structures, and programming paradigms.',
    department: 'Computer Science',
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 2,
    name: 'Data Structures and Algorithms',
    code: 'CS201',
    description: 'Advanced study of data structures including trees, graphs, and hash tables with algorithm analysis.',
    department: 'Computer Science',
    createdAt: '2024-01-20T14:45:00Z',
  },
  {
    id: 3,
    name: 'Web Development Fundamentals',
    code: 'CS301',
    description: 'Introduction to web technologies including HTML, CSS, JavaScript, and responsive design.',
    department: 'Computer Science',
    createdAt: '2024-02-01T09:15:00Z',
  },
  {
    id: 4,
    name: 'Database Management Systems',
    code: 'CS401',
    description: 'Design and implementation of relational databases, SQL queries, and database optimization.',
    department: 'Computer Science',
    createdAt: '2024-02-10T11:20:00Z',
  },
  {
    id: 5,
    name: 'Linear Algebra',
    code: 'MATH101',
    description: 'Vectors, matrices, eigenvalues, and applications in computer science and engineering.',
    department: 'Mathematics',
    createdAt: '2024-02-15T13:40:00Z',
  },
  {
    id: 6,
    name: 'Calculus II',
    code: 'MATH102',
    description: 'Integration techniques, differential equations, and series convergence.',
    department: 'Mathematics',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 7,
    name: 'Physics I: Mechanics',
    code: 'PHYS101',
    description: 'Classical mechanics including kinematics, dynamics, energy, and momentum.',
    department: 'Physics',
    createdAt: '2024-03-01T08:30:00Z',
  },
  {
    id: 8,
    name: 'Physics II: Electricity and Magnetism',
    code: 'PHYS102',
    description: 'Electric fields, magnetic forces, circuits, and electromagnetic waves.',
    department: 'Physics',
    createdAt: '2024-03-05T15:20:00Z',
  },
  {
    id: 9,
    name: 'English Composition',
    code: 'ENG101',
    description: 'Academic writing skills including essay structure, research, and critical thinking.',
    department: 'English',
    createdAt: '2024-03-10T12:00:00Z',
  },
  {
    id: 10,
    name: 'Literature and Analysis',
    code: 'ENG202',
    description: 'Critical reading and analysis of classic and contemporary literature.',
    department: 'English',
    createdAt: '2024-03-15T14:30:00Z',
  },
];
